"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-07-27 13:02:45.604025
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soato_id', sa.Integer(), nullable=True),
    sa.Column('name_uz', sa.String(length=120), nullable=False),
    sa.Column('name_oz', sa.String(length=120), nullable=True),
    sa.Column('name_ru', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regions'))
    )
    op.create_table('scheduler_leases',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('holder', sa.String(length=64), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_scheduler_leases'))
    )
    with op.batch_alter_table('scheduler_leases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduler_leases_expires_at'), ['expires_at'], unique=False)

    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('soato_id', sa.Integer(), nullable=True),
    sa.Column('name_uz', sa.String(length=120), nullable=False),
    sa.Column('name_oz', sa.String(length=120), nullable=True),
    sa.Column('name_ru', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_districts_region_id_regions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_districts'))
    )
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_districts_region_id'), ['region_id'], unique=False)

    op.create_table('mahallas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('name_normalized', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('estimated_households', sa.Integer(), nullable=True),
    sa.Column('petition_threshold', sa.Integer(), nullable=True),
    sa.Column('raisi_user_id', sa.Integer(), nullable=True),
    sa.Column('pinned_post_id', sa.Integer(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name=op.f('fk_mahallas_district_id_districts')),
    sa.ForeignKeyConstraint(['pinned_post_id'], ['posts.id'], name='fk_mahallas_pinned_post_id_posts', use_alter=True),
    sa.ForeignKeyConstraint(['raisi_user_id'], ['users.id'], name='fk_mahallas_raisi_user_id_users', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mahallas')),
    sa.UniqueConstraint('district_id', 'name_normalized', name=op.f('uq_mahallas_district_id'))
    )
    with op.batch_alter_table('mahallas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mahallas_district_id'), ['district_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mahallas_name_normalized'), ['name_normalized'], unique=False)

    op.create_table('mahalla_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mahalla_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mahalla_id'], ['mahallas.id'], name=op.f('fk_mahalla_contacts_mahalla_id_mahallas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mahalla_contacts'))
    )
    with op.batch_alter_table('mahalla_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mahalla_contacts_mahalla_id'), ['mahalla_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('photo_url', sa.String(length=400), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('mahalla_id', sa.Integer(), nullable=True),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.Column('rep_month', sa.Integer(), nullable=False),
    sa.Column('rep_alltime', sa.Integer(), nullable=False),
    sa.Column('rep_month_key', sa.String(length=7), nullable=True),
    sa.Column('banned_until', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('lang', sa.String(length=3), nullable=False),
    sa.Column('tg_dm_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name='fk_users_household_id_households', use_alter=True),
    sa.ForeignKeyConstraint(['mahalla_id'], ['mahallas.id'], name=op.f('fk_users_mahalla_id_mahallas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_mahalla_id'), ['mahalla_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_tg_id'), ['tg_id'], unique=True)

    op.create_table('ban_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mahalla_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('until', sa.DateTime(), nullable=True),
    sa.Column('permanent', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_ban_records_created_by_users')),
    sa.ForeignKeyConstraint(['mahalla_id'], ['mahallas.id'], name=op.f('fk_ban_records_mahalla_id_mahallas')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ban_records_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ban_records'))
    )
    with op.batch_alter_table('ban_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ban_records_user_id'), ['user_id'], unique=False)

    op.create_table('event_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('mahalla_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mahalla_id'], ['mahallas.id'], name=op.f('fk_event_log_mahalla_id_mahallas')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_event_log_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_log'))
    )
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_log_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_log_user_id'), ['user_id'], unique=False)

    op.create_table('households',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mahalla_id', sa.Integer(), nullable=False),
    sa.Column('family_name', sa.String(length=150), nullable=False),
    sa.Column('resident_count', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=200), nullable=True),
    sa.Column('family_history', sa.Text(), nullable=True),
    sa.Column('generations_here', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_households_created_by_users')),
    sa.ForeignKeyConstraint(['mahalla_id'], ['mahallas.id'], name=op.f('fk_households_mahalla_id_mahallas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_households'))
    )
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_households_mahalla_id'), ['mahalla_id'], unique=False)

    op.create_table('month_honors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mahalla_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('winner_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mahalla_id'], ['mahallas.id'], name=op.f('fk_month_honors_mahalla_id_mahallas')),
    sa.ForeignKeyConstraint(['winner_user_id'], ['users.id'], name=op.f('fk_month_honors_winner_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_month_honors')),
    sa.UniqueConstraint('mahalla_id', 'month', name=op.f('uq_month_honors_mahalla_id'))
    )
    with op.batch_alter_table('month_honors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_month_honors_mahalla_id'), ['mahalla_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mahalla_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('event', sa.String(length=40), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('text', sa.String(length=300), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mahalla_id'], ['mahallas.id'], name=op.f('fk_notifications_mahalla_id_mahallas')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_read'), ['read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('petitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mahalla_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('estimated_households', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mahalla_id'], ['mahallas.id'], name=op.f('fk_petitions_mahalla_id_mahallas')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_petitions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_petitions')),
    sa.UniqueConstraint('mahalla_id', 'user_id', name=op.f('uq_petitions_mahalla_id'))
    )
    with op.batch_alter_table('petitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_petitions_mahalla_id'), ['mahalla_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_petitions_user_id'), ['user_id'], unique=False)

    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mahalla_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=300), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('goal', sa.String(length=200), nullable=True),
    sa.Column('charity_goal_amount', sa.Integer(), nullable=True),
    sa.Column('charity_collected_amount', sa.Integer(), nullable=False),
    sa.Column('charity_updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_helper_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_posts_author_id_users')),
    sa.ForeignKeyConstraint(['mahalla_id'], ['mahallas.id'], name=op.f('fk_posts_mahalla_id_mahallas')),
    sa.ForeignKeyConstraint(['resolved_helper_id'], ['users.id'], name=op.f('fk_posts_resolved_helper_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts'))
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_mahalla_id'), ['mahalla_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_type'), ['type'], unique=False)

    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mahalla_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('seconds_needed', sa.Integer(), nullable=False),
    sa.Column('voting_opens_at', sa.DateTime(), nullable=True),
    sa.Column('voting_closes_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_proposals_author_id_users')),
    sa.ForeignKeyConstraint(['mahalla_id'], ['mahallas.id'], name=op.f('fk_proposals_mahalla_id_mahallas')),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], name=op.f('fk_proposals_target_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposals'))
    )
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposals_mahalla_id'), ['mahalla_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('mahalla_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mahalla_id'], ['mahallas.id'], name=op.f('fk_reports_mahalla_id_mahallas')),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_reports_reporter_id_users')),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_reports_resolved_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_mahalla_id'), ['mahalla_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_target_type'), ['target_type'], unique=False)

    op.create_table('reputation_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mahalla_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mahalla_id'], ['mahallas.id'], name=op.f('fk_reputation_entries_mahalla_id_mahallas')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reputation_entries_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reputation_entries'))
    )
    with op.batch_alter_table('reputation_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reputation_entries_mahalla_id'), ['mahalla_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reputation_entries_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_reputation_entries_user_id'), ['user_id'], unique=False)

    op.create_table('user_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_activity_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_activity')),
    sa.UniqueConstraint('user_id', 'day', name=op.f('uq_user_activity_user_id'))
    )
    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_activity_user_id'), ['user_id'], unique=False)

    op.create_table('household_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_household_images_household_id_households')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_household_images'))
    )
    with op.batch_alter_table('household_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_household_images_household_id'), ['household_id'], unique=False)

    op.create_table('household_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('is_elder', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_household_members_household_id_households')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_household_members_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_household_members'))
    )
    with op.batch_alter_table('household_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_household_members_household_id'), ['household_id'], unique=False)

    op.create_table('poll_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=80), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_poll_options_post_id_posts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_poll_options'))
    )
    with op.batch_alter_table('poll_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poll_options_post_id'), ['post_id'], unique=False)

    op.create_table('post_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_comments_post_id_posts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_post_comments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_comments'))
    )
    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_comments_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_comments_user_id'), ['user_id'], unique=False)

    op.create_table('post_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_images_post_id_posts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_images'))
    )
    with op.batch_alter_table('post_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_images_post_id'), ['post_id'], unique=False)

    op.create_table('post_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_reactions_post_id_posts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_post_reactions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_reactions')),
    sa.UniqueConstraint('post_id', 'user_id', name=op.f('uq_post_reactions_post_id'))
    )
    with op.batch_alter_table('post_reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_reactions_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_reactions_user_id'), ['user_id'], unique=False)

    op.create_table('post_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_responses_post_id_posts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_post_responses_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_responses')),
    sa.UniqueConstraint('post_id', 'user_id', name=op.f('uq_post_responses_post_id'))
    )
    with op.batch_alter_table('post_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_responses_post_id'), ['post_id'], unique=False)

    op.create_table('proposal_seconds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], name=op.f('fk_proposal_seconds_proposal_id_proposals')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_proposal_seconds_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposal_seconds')),
    sa.UniqueConstraint('proposal_id', 'user_id', name=op.f('uq_proposal_seconds_proposal_id'))
    )
    with op.batch_alter_table('proposal_seconds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposal_seconds_proposal_id'), ['proposal_id'], unique=False)

    op.create_table('service_offerings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('mahalla_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('price', sa.String(length=80), nullable=True),
    sa.Column('contact', sa.String(length=120), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_service_offerings_created_by_users')),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_service_offerings_household_id_households')),
    sa.ForeignKeyConstraint(['mahalla_id'], ['mahallas.id'], name=op.f('fk_service_offerings_mahalla_id_mahallas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_offerings'))
    )
    with op.batch_alter_table('service_offerings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_offerings_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_offerings_mahalla_id'), ['mahalla_id'], unique=False)

    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('choice', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], name=op.f('fk_votes_proposal_id_proposals')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_votes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_votes')),
    sa.UniqueConstraint('proposal_id', 'user_id', name=op.f('uq_votes_proposal_id'))
    )
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_votes_proposal_id'), ['proposal_id'], unique=False)

    op.create_table('vouches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('voucher_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_vouches_household_id_households')),
    sa.ForeignKeyConstraint(['voucher_user_id'], ['users.id'], name=op.f('fk_vouches_voucher_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vouches')),
    sa.UniqueConstraint('household_id', 'voucher_user_id', name=op.f('uq_vouches_household_id'))
    )
    with op.batch_alter_table('vouches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vouches_household_id'), ['household_id'], unique=False)

    op.create_table('household_join_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_household_join_requests_household_id_households')),
    sa.ForeignKeyConstraint(['member_id'], ['household_members.id'], name=op.f('fk_household_join_requests_member_id_household_members')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_household_join_requests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_household_join_requests')),
    sa.UniqueConstraint('household_id', 'user_id', name=op.f('uq_household_join_requests_household_id'))
    )
    with op.batch_alter_table('household_join_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_household_join_requests_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_household_join_requests_user_id'), ['user_id'], unique=False)

    op.create_table('poll_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['poll_options.id'], name=op.f('fk_poll_votes_option_id_poll_options')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_poll_votes_post_id_posts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_poll_votes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_poll_votes')),
    sa.UniqueConstraint('post_id', 'user_id', name=op.f('uq_poll_votes_post_id'))
    )
    with op.batch_alter_table('poll_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poll_votes_option_id'), ['option_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poll_votes_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poll_votes_user_id'), ['user_id'], unique=False)

    op.create_table('service_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service_offerings.id'], name=op.f('fk_service_images_service_id_service_offerings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_images'))
    )
    with op.batch_alter_table('service_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_images_service_id'), ['service_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_images_service_id'))

    op.drop_table('service_images')
    with op.batch_alter_table('poll_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poll_votes_user_id'))
        batch_op.drop_index(batch_op.f('ix_poll_votes_post_id'))
        batch_op.drop_index(batch_op.f('ix_poll_votes_option_id'))

    op.drop_table('poll_votes')
    with op.batch_alter_table('household_join_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_household_join_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_household_join_requests_household_id'))

    op.drop_table('household_join_requests')
    with op.batch_alter_table('vouches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vouches_household_id'))

    op.drop_table('vouches')
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_votes_proposal_id'))

    op.drop_table('votes')
    with op.batch_alter_table('service_offerings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_offerings_mahalla_id'))
        batch_op.drop_index(batch_op.f('ix_service_offerings_household_id'))

    op.drop_table('service_offerings')
    with op.batch_alter_table('proposal_seconds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposal_seconds_proposal_id'))

    op.drop_table('proposal_seconds')
    with op.batch_alter_table('post_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_responses_post_id'))

    op.drop_table('post_responses')
    with op.batch_alter_table('post_reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_reactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_post_reactions_post_id'))

    op.drop_table('post_reactions')
    with op.batch_alter_table('post_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_images_post_id'))

    op.drop_table('post_images')
    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_post_comments_post_id'))
        batch_op.drop_index(batch_op.f('ix_post_comments_created_at'))

    op.drop_table('post_comments')
    with op.batch_alter_table('poll_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poll_options_post_id'))

    op.drop_table('poll_options')
    with op.batch_alter_table('household_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_household_members_household_id'))

    op.drop_table('household_members')
    with op.batch_alter_table('household_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_household_images_household_id'))

    op.drop_table('household_images')
    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_activity_user_id'))

    op.drop_table('user_activity')
    with op.batch_alter_table('reputation_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reputation_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_reputation_entries_month'))
        batch_op.drop_index(batch_op.f('ix_reputation_entries_mahalla_id'))

    op.drop_table('reputation_entries')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_target_type'))
        batch_op.drop_index(batch_op.f('ix_reports_target_id'))
        batch_op.drop_index(batch_op.f('ix_reports_status'))
        batch_op.drop_index(batch_op.f('ix_reports_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_reports_mahalla_id'))
        batch_op.drop_index(batch_op.f('ix_reports_created_at'))

    op.drop_table('reports')
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposals_mahalla_id'))

    op.drop_table('proposals')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_type'))
        batch_op.drop_index(batch_op.f('ix_posts_mahalla_id'))
        batch_op.drop_index(batch_op.f('ix_posts_created_at'))

    op.drop_table('posts')
    with op.batch_alter_table('petitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_petitions_user_id'))
        batch_op.drop_index(batch_op.f('ix_petitions_mahalla_id'))

    op.drop_table('petitions')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('month_honors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_month_honors_mahalla_id'))

    op.drop_table('month_honors')
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_households_mahalla_id'))

    op.drop_table('households')
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_log_event'))
        batch_op.drop_index(batch_op.f('ix_event_log_created_at'))

    op.drop_table('event_log')
    with op.batch_alter_table('ban_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ban_records_user_id'))

    op.drop_table('ban_records')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tg_id'))
        batch_op.drop_index(batch_op.f('ix_users_mahalla_id'))

    op.drop_table('users')
    with op.batch_alter_table('mahalla_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mahalla_contacts_mahalla_id'))

    op.drop_table('mahalla_contacts')
    with op.batch_alter_table('mahallas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mahallas_name_normalized'))
        batch_op.drop_index(batch_op.f('ix_mahallas_district_id'))

    op.drop_table('mahallas')
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_districts_region_id'))

    op.drop_table('districts')
    with op.batch_alter_table('scheduler_leases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduler_leases_expires_at'))

    op.drop_table('scheduler_leases')
    op.drop_table('regions')
    # ### end Alembic commands ###
