"""utility board (chiroq bormi)

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-30 12:47:53.643751
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utility_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mahalla_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('bucket', sa.String(length=13), nullable=False),
    sa.Column('households', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mahalla_id'], ['mahallas.id'], name=op.f('fk_utility_alerts_mahalla_id_mahallas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_utility_alerts')),
    sa.UniqueConstraint('mahalla_id', 'kind', 'bucket', name=op.f('uq_utility_alerts_mahalla_id'))
    )
    with op.batch_alter_table('utility_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utility_alerts_mahalla_id'), ['mahalla_id'], unique=False)

    op.create_table('utility_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mahalla_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_utility_windows_created_by_users')),
    sa.ForeignKeyConstraint(['mahalla_id'], ['mahallas.id'], name=op.f('fk_utility_windows_mahalla_id_mahallas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_utility_windows'))
    )
    with op.batch_alter_table('utility_windows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utility_windows_mahalla_id'), ['mahalla_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_utility_windows_starts_at'), ['starts_at'], unique=False)

    op.create_table('utility_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mahalla_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.Column('street', sa.String(length=200), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('is_out', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_utility_reports_household_id_households')),
    sa.ForeignKeyConstraint(['mahalla_id'], ['mahallas.id'], name=op.f('fk_utility_reports_mahalla_id_mahallas')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_utility_reports_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_utility_reports'))
    )
    with op.batch_alter_table('utility_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utility_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_utility_reports_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_utility_reports_mahalla_id'), ['mahalla_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_utility_reports_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utility_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utility_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_utility_reports_mahalla_id'))
        batch_op.drop_index(batch_op.f('ix_utility_reports_kind'))
        batch_op.drop_index(batch_op.f('ix_utility_reports_created_at'))

    op.drop_table('utility_reports')
    with op.batch_alter_table('utility_windows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utility_windows_starts_at'))
        batch_op.drop_index(batch_op.f('ix_utility_windows_mahalla_id'))

    op.drop_table('utility_windows')
    with op.batch_alter_table('utility_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utility_alerts_mahalla_id'))

    op.drop_table('utility_alerts')
    # ### end Alembic commands ###
