"""price board

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-30 13:15:12.371195
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('mahalla_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=20), nullable=False),
    sa.Column('som', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=80), nullable=True),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name=op.f('fk_price_reports_district_id_districts')),
    sa.ForeignKeyConstraint(['mahalla_id'], ['mahallas.id'], name=op.f('fk_price_reports_mahalla_id_mahallas')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_price_reports_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_reports')),
    sa.UniqueConstraint('user_id', 'item', 'day', name=op.f('uq_price_reports_user_id'))
    )
    with op.batch_alter_table('price_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_reports_district_id'), ['district_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_reports_item'), ['item'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_reports_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_price_reports_item'))
        batch_op.drop_index(batch_op.f('ix_price_reports_district_id'))
        batch_op.drop_index(batch_op.f('ix_price_reports_created_at'))

    op.drop_table('price_reports')
    # ### end Alembic commands ###
