"""away members

Revision ID: 0005
Revises: 0004
Create Date: 2026-07-30 13:24:06.858957
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('away_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('mahalla_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_away_members_approved_by_users')),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_away_members_household_id_households')),
    sa.ForeignKeyConstraint(['mahalla_id'], ['mahallas.id'], name=op.f('fk_away_members_mahalla_id_mahallas')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_away_members_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_away_members')),
    sa.UniqueConstraint('user_id', 'household_id', name=op.f('uq_away_members_user_id'))
    )
    with op.batch_alter_table('away_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_away_members_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_away_members_mahalla_id'), ['mahalla_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_away_members_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('away_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_away_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_away_members_mahalla_id'))
        batch_op.drop_index(batch_op.f('ix_away_members_household_id'))

    op.drop_table('away_members')
    # ### end Alembic commands ###
